name: Release to PyPI

on:
  push:
    tags:
        - 'v0.[0-9]+.[0-9]+'

jobs:
  deployment:
    runs-on: ubuntu-22.04
    environment:
        name: deploy-to-pypi
        url: https://pypi.org/project/ropt-nomad/
    permissions:
        id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name}}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.10"
    - name: Build distribution
      run: |
        python -m pip install build
        python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
