name: Release to PyPI

on:
  push:
    tags:
        - 'v0.[0-9]+.[0-9]+'

jobs:
  deployment:
    runs-on: ubuntu-22.04
    environment:
        name: deploy-to-pypi
        url: https://pypi.org/project/ropt-nomad/
    permissions:
        id-token: write
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ github.ref_name}}
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"
    - name: Install uv
      uses: astral-sh/setup-uv@v2
      with:
          enable-cache: true
    - name: Build and deploy
      run: uv build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@release/v1
